/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "API": {
        "endpoints": [
            {
                "name": "amplify-test-api",
                "endpoint": "https://m5be9u11f0.execute-api.us-west-2.amazonaws.com/default"
            }
        ]
    }
};


export default awsmobile;
