/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
    API: {
      endpoints: [
        {
          name: "amplify-test-api",
          endpoint: "https://m5be9u11f0.execute-api.us-west-2.amazonaws.com/default",  // Use your actual API Gateway URL here
        },
      ],
    },
  };
  
  export default awsconfig;